---
application:
  name: "socket-io-echo-server"
  project: "wefef"
  organization: "QoveryCommunity"
databases:
- type: "REDIS"
  name: "leaf"
  version: "5"
routers:
- name: "main-socket-io-echo-server"
  routes:
  - application_name: "socket-io-echo-server"
    paths:
    - "/*"
